---

- name: "Instalando os pre-requisitos"
  apt:
    name: "{{ pacotes_debian }}"
    state: present
    update_cache: yes
  tags:
    - deps


- name: "Importando a chave do repositorio do Jenkins"
  apt_key: 
    url: "https://pkg.jenkins.io/debian-stable/jenkins.io.key"
    state: present
  tags:
    - repo


- name: "Adicionando o Repositorio do Jenkins"
  apt_repository:
    repo: "deb https://pkg.jenkins.io/debian-stable binary/"
    state: present
    filename: jenkins
    update_cache: yes
  tags:
    - repo


- name: "Instalando o Jenkins"
  apt:
    name: jenkins
    state: present
    update_cache: yes
  notify:
    - Start Jenkins
  tags:
    - jenkins